### ISSUE TITLE
method header should print Status header first

### ISSUE THREAD

**Issue by zopsicle** [jonathanstowe/raku-fastcgi-nativecall#4]
The Status header should be the first header for compatibility with some servers such as Caddy. Currently headers are printed in whatever order the hash puts them in.

Example:

```raku
$fcgi.header(Status => 404, Content-Type => 'text/html');
# Sometimes Status comes last because Hash has an unpredictable order.
```

**Comment by jonathanstowe** [comment]
Yeah that's fixable, have you got a sample configuration for e.g. caddy so I can test this?

**Comment by zopsicle** [comment]
Nevermind! I was misusing the API, like this:

```raku
$fcgi.header(Status => 404, $header);
```

But this passes Status as a argument, not as a pair, and apparently hash slurping does not work that way.

Solution:

```raku
$fcgi.header(Status => 404, |$header);
```
