### ISSUE TITLE
Fails tests on FreeBSD

### ISSUE THREAD

**Issue by pprocacci** [jonathanstowe/raku-fastcgi-nativecall#5]
Not sure how these differ:

#zef install FastCGI::NativeCall
```
===> Searching for: FastCGI::NativeCall
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Building: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
===> Building [OK] for FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
===> Testing: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
[FastCGI::NativeCall]     # Failed test 'opened socket'
[FastCGI::NativeCall]     # at t/010-basic.t line 15
[FastCGI::NativeCall]     # You failed 1 test of 3
[FastCGI::NativeCall] # Failed test 'original interface'
[FastCGI::NativeCall] # at t/010-basic.t line 12
[FastCGI::NativeCall] bind/listen: Address already in use
===> Testing [FAIL]: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
Aborting due to test failure: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0> (use --force-test to override)
```

#zef install .  (after downloading the git repo by hand)
```
===> Building: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
===> Building [OK] for FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
===> Testing: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
===> Testing [OK] for FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
===> Installing: FastCGI::NativeCall:ver<0.0.6>:auth<github:carbin>:api<1.0>
```

The preferred installation method is obviously the former.

**Comment by jonathanstowe** [comment]
They *should* be the same but I guess there is a chance they differ.

I'll need to make a FreeBSD VM to test this on, bear with me.

**Comment by jonathanstowe** [comment]
Didn't need to make a VM to replicate, the CPAN version fails what is on github doesn't.  I'll look at the other thing in #6 and then try and make a release as soon as I can.

**Comment by jonathanstowe** [comment]
Okay, I've worked out why this is happening.  I had inadvertently included the `fcgi_config.h` in the CPAN tarball, thus meaning the configure step is never run, the file is explicitly excluded by `.gitignore` from the git repo.  Obviously it works fine both ways on my local machine where the configure was run.

I'll obviously have to make another release to remedy this.

**Comment by jonathanstowe** [comment]
I'm going to release a fix for this immediately as it will probably be effecting everyone who is using a different OS release to the machine I build the tarball on.  The #6 seems a bit less tractable.
