### ISSUE TITLE
Unix domain socket - truncated filename

### ISSUE THREAD

**Issue by pprocacci** [jonathanstowe/raku-fastcgi-nativecall#6]
Given the example in the readme:

```
#!/usr/bin/env perl6

use FastCGI::NativeCall;

my $fcgi = FastCGI::NativeCall.new(path => "/tmp/fastcgi.sock", backlog => 32 );

my $count = 0;

while $fcgi.accept() {
        say $fcgi.env;
    $fcgi.header(Content-Type => "text/html");
    $fcgi.Print("{ ++$count }");
}
```

.. and low and behold ...

```
# ./test.pl6
^C
# ls -l /tmp/fastcgi.so*
srwxr-xr-x  1 root  wheel  0 May 28 19:29 /tmp/fastcgi.soc
```

This being ran on FreeBSD 12.

**Comment by jonathanstowe** [comment]
That sucks,  do you have a specific version of FreeBSD 12 or is `12.1-RELEASE-p1` enough to tickle it?  I'll probably need to make a VM to test this because the FreeBSD host I usually test on has a different kernel and userland right now and either of those could cause the problem.

**Comment by pprocacci** [comment]
I am camping ATM so I won't be able to follow up in this till Sunday
night.  I'm using FreeBSD 12 stable.  I can test like you on any version
though it'll have to again wait till Monday.

**Comment by jonathanstowe** [comment]
Struggling to replicate this at the moment.

**Comment by jonathanstowe** [comment]
Tried it on a  pristine VM and it still works as expected:

```
$ ls /tmp
fastcgi.sock
$ uname -a
FreeBSD zubzub 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  i386
$ rakudo -v
This is Rakudo version 2020.05.1-207-g6ead4ce16 built on MoarVM version 2020.05
implementing Raku 6.d.
```

**Comment by jonathanstowe** [comment]
Could you share your `rakudo` version, the contents of the `ext/Makefile` and the `ext/fcgi_config.h`  so I can better replicate your environment?

**Comment by pprocacci** [comment]
Since installing 0.0.7 I can no longer reproduce this myself.
I can only imagine that my bug report as detailed in #5 was somehow the cause of this bug as I was playing w/ --force during the install process.

In an attempt to confirm that I tried various install options to attempt to install the older module via zef but I was incapable of piecing together a command that worked.  This isn't really all that important.

Let's let this be for now, and I'll reopen the case as necessary should the problem return.

**Comment by jonathanstowe** [comment]
Ah, yes if you had used `--force` it would have wound up with totally wrong definitions of the maximum length of the unix socket _address_ (the include files differ in detail on Linux vs FreeBSD,) I'm actually surprised it didn't segfault.

Ho, hum.  I'll close this now and we can re-open if it recurs.

Thanks for the report.
